plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "asimov.gemspec"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "lib/asimov/api_v1/api_error_translator.rb"

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SubjectStub:
  Exclude:
    - "spec/asimov/api_v1/**/*.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  AllowedCompactTypes: ['MissingRequiredParameterError']

Style/StringLiterals:
  EnforcedStyle: double_quotes
